strip cruft from before single-use slaves

diff --git a/slave/ci-slave-run b/slave/ci-slave-run
--- a/slave/ci-slave-run
+++ b/slave/ci-slave-run
@@ -1,5 +1,10 @@
 #!/bin/bash -xe
 
+if [ -d /opt/stack ]; then
+    echo "ERROR: attempt to re-use devstack node"
+    exit 1
+fi
+
 if [ -z $ZUUL_PROJECT ]; then
     export ZUUL_PROJECT=openstack/neutron
 fi
@@ -22,15 +27,8 @@ export DEVSTACK_GATE_TEMPEST_REGEX='(?!.*\[.*\bslow\b.*\])(tempest.api.network|t
 
 echo "HOSTNAME `hostname`"
 
-if [ -z "$SINGLE_USE" ]; then
-    $WORKSPACE/neutron-thirdparty-ci/slave/ci-slave-pre-cleanup
-    $WORKSPACE/neutron-thirdparty-ci/slave/ci-slave-reset-a10
-else
-    # Start spinning up an appliance now; we'll check it in the pre-test-hook
-    $WORKSPACE/neutron-thirdparty-ci/slave/pre-setup
-    $WORKSPACE/neutron-thirdparty-ci/slave/a10-run
-fi
-
+# Tweak the features a bit; swift and cinder waste a bunch of RAM/disk,
+# and we do not test them at all.
 cat devstack-gate/features.yaml \
   | sed -e 's/master\: \[default.*$/master: \[default, ceilometer, glance, horizon, nova, keystone\]/' \
   | sed -e 's/juno\: \[default.*$/juno: \[default, ceilometer, glance, horizon, nova, keystone\]/' \
@@ -55,6 +53,8 @@ export -f post_test_hook
 # export -f gate_hook
 
 export RE_EXEC=true
+
+$WORKSPACE/neutron-thirdparty-ci/slave/pre-setup-hook
 
 cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
 set +e
